import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import Hero from '@/components/sections/Hero'
import Spotlight from '@/components/sections/Spotlight'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray2">
      <Navbar/>
      <Hero/>
      <Spotlight className={"bg-gray1"} styles="border" mainTitle={"Spotlight "} btnName="See all aalto University news"/>
      <Spotlight className={"bg-gray2"} mainTitle={"Join our many events"}  btnName="See all events" />
      </main>
    </>
  )
}
