import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/layout/Navbar'
import Hero from '@/components/sections/Hero'
import Spotlight from '@/components/sections/Spotlight'
import Explorer from '@/components/sections/Explorer'
import Studies from '@/components/sections/Studies'
import Information from '@/components/sections/Information'
import Research from '@/components/sections/Research'
import Follow from '@/components/sections/Follow'
import Footer from '@/components/layout/Footer'
import img11 from "../public/images/img11.jpg"
import img30 from "../public/images/img30.jpg"
import img31 from "../public/images/img31.jpg"
import img32 from "../public/images/img33.jpg"
import img33 from "../public/images/img33.png"
import img34 from "../public/images/img34.png"


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Aalto University</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray2">
        <Hero/>
        <Spotlight className={"bg-gray1"} styles="border" img1={img11} img2={img30} img3={img31} mainTitle={"Spotlight "} btnName="See all aalto University news"/>
        <Spotlight className={"bg-gray2"} mainTitle={"Join our many events"} img1={img33} img2={img32} img3={img34}   btnName="See all events" />
        <Explorer />
        <Studies />
        <Information />
        <Research />
        <Follow />
      </main>
    </>
  )
}
